In [1]:
import numpy as np
import torch

c:\Users\jakko\Anaconda3\envs\knn\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [95]:
a = torch.zeros(20, dtype=int).reshape(2,2,5)
a[0,0,0] = 1
a[0,1,0] = 2
a[1,0,0] = 2
a[1,1,0] = 2
a[1,0,1] = 1
a[1,1,1] = 2
a[0,0,4] = 1
a[1,0,4] = -1
b = torch.arange(0, 18).reshape(2,1,3,3)
print(a)
print(b)

tensor([[[ 1,  0,  0,  0,  1],
         [ 2,  0,  0,  0,  0]],

        [[ 2,  1,  0,  0, -1],
         [ 2,  2,  0,  0,  0]]])
tensor([[[[ 0,  1,  2],
          [ 3,  4,  5],
          [ 6,  7,  8]]],


        [[[ 9, 10, 11],
          [12, 13, 14],
          [15, 16, 17]]]])


In [85]:
a

tensor([[[1, 0, 0, 0, 0],
         [2, 0, 0, 0, 0]],

        [[2, 1, 0, 0, 0],
         [2, 2, 0, 0, 0]]])

In [91]:
print(a[:,:,:4][:,:,0])
print(a[:,:,:4][:,:,1])
print(a[:,:,:4][:,:,2])
print(a[:,:,:4][:,:,3])

tensor([[1, 2],
        [2, 2]])
tensor([[0, 0],
        [1, 2]])
tensor([[0, 0],
        [0, 0]])
tensor([[0, 0],
        [0, 0]])


In [122]:
print(b.squeeze())
print(b.squeeze()[:,1,0])

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])
tensor([ 3, 12])


In [125]:
# torch.take_along_dim(b.squeeze(), torch.tensor([[0],[1]]), dim=0)
# row = torch.tensor([0,1])
# col = torch.tensor([0,1])
print(b.squeeze())
print(a)
row1 = a[:,:,:4][:,:,0]
col1 = a[:,:,:4][:,:,1]
row2 = a[:,:,:4][:,:,2]
col2 = a[:,:,:4][:,:,3]
print(left := b.squeeze()[:, row1, col1][:,0])
print(right := b.squeeze()[:, row2, col2][:,0])

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])
tensor([[[ 1,  0,  0,  0,  1],
         [ 2,  0,  0,  0,  0]],

        [[ 2,  1,  0,  0, -1],
         [ 2,  2,  0,  0,  0]]])
tensor([[ 3,  6],
        [12, 15]])
tensor([[0, 0],
        [9, 9]])


In [142]:
a[:,:,4]

zeros = torch.zeros_like(a[:,:,4], dtype=torch.float)
log = torch.log(1 + torch.exp(-left + right))


val1 = torch.where(a[:,:,4] == 1 , torch.log(1 + torch.exp(-left + right)), zeros)
val2 = torch.where(a[:,:,4] == -1 , torch.log(1 + torch.exp(left - right)), zeros)
val3 = torch.where(a[:,:,4] == 0 , torch.square(left - right).type(torch.float), zeros)

print(val1 + val2 + val3)
torch.sum(val1 + val2 + val3, dim=1)


tensor([[ 0.0486, 36.0000],
        [ 3.0486, 36.0000]])


tensor([36.0486, 39.0486])